--CRIANDO A TABELA DE CLIENTE
CREATE TABLE CLIENTE(
	IDCLIENTE		UNIQUEIDENTIFIER		NOT NULL,
	NOME			NVARCHAR(150)			NOT NULL,
	EMAIL			NVARCHAR(100)			NOT NULL,
	DATACADASTRO	DATETIME				NOT NULL,
	PRIMARY KEY(IDCLIENTE))
GO

--CRIANDO A PROCECURE PARA CADASTRAR CLIENTE
CREATE PROCEDURE SP_INSERIRCLIENTE
	@NOME		NVARCHAR(150),	
	@EMAIL		NVARCHAR(100)
AS
BEGIN
	BEGIN TRANSACTION
	INSERT INTO CLIENTE(IDCLIENTE, NOME, EMAIL, DATACADASTRO)
	VALUES(NEWID(), @NOME, @EMAIL, GETDATE())
	COMMIT
END
GO

--CRIANDO A PROCECURE PARA ALTERAR CLIENTE
CREATE PROCEDURE SP_ALTERARCLIENTE
	@IDCLIENTE	UNIQUEIDENTIFIER,
	@NOME		NVARCHAR(150),	
	@EMAIL		NVARCHAR(100)
AS
BEGIN
	BEGIN TRANSACTION
	UPDATE CLIENTE
	SET
		NOME = @NOME,
		EMAIL = @EMAIL
	WHERE
		IDCLIENTE = @IDCLIENTE
	COMMIT
END
GO

--CRIANDO A PROCECURE PARA EXCLUIR CLIENTE
CREATE PROCEDURE SP_EXCLUIRCLIENTE
	@IDCLIENTE	UNIQUEIDENTIFIER
AS
BEGIN
	BEGIN TRANSACTION
	DELETE FROM CLIENTE
	WHERE IDCLIENTE = @IDCLIENTE
	COMMIT
END
GO




